// Writes the licences of every package that ends up in the bundle, with their texts, to stdout:
//
//   npm run licenses
//
// The bundle itself carries no licence comments, and the licences ask that their notices travel
// with the code, so this file is served next to the script.

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

const meta = path.join(process.env.TMPDIR || "/tmp", "webvendor-meta.json");
execFileSync("./node_modules/.bin/esbuild", [
  "entry.js", "--bundle", "--format=esm", "--minify", "--target=es2022", "--platform=browser", "--legal-comments=none",
  `--metafile=${meta}`, `--outfile=${path.join(process.env.TMPDIR || "/tmp", "webvendor-check.js")}`,
], { stdio: "ignore" });

const inputs = Object.keys(Object.values(JSON.parse(fs.readFileSync(meta, "utf8")).outputs)[0].inputs);
const packages = new Set();
for (const file of inputs) {
  const i = file.lastIndexOf("node_modules/");
  if (i < 0) continue;
  const parts = file.slice(i + "node_modules/".length).split("/");
  packages.add(parts[0].startsWith("@") ? `${parts[0]}/${parts[1]}` : parts[0]);
}

let out = "Licences of the packages bundled into atproto-oauth-client-browser.js\n(generated by internal/feedgen/webvendor: npm run licenses)\n\n";
for (const name of [...packages].sort()) {
  const dir = path.join("node_modules", name);
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
  const repo = pkg.repository && (pkg.repository.url || pkg.repository) || "";
  out += `${"=".repeat(80)}\n${name}@${pkg.version}  (${typeof pkg.license === "string" ? pkg.license : JSON.stringify(pkg.license)})\n${repo}\n\n`;
  const file = fs.readdirSync(dir).find((n) => /^(licen[sc]e|copying)/i.test(n));
  out += file ? `${fs.readFileSync(path.join(dir, file), "utf8").trim()}\n\n` : "(no licence file in the package; see its licence field above)\n\n";
}
process.stdout.write(out);
